### ISSUE TITLE
Attempting to get codepen example working

### ISSUE THREAD

**Issue by opike** [bvaughn/react-resizable-panels#157]
I'm tyring to set up a codepen example to work here:
https://codepen.io/opike99/pen/OJaVbNd

No errors are being generated but there isn't anything being rendered either.

I tried adding some of the styling from the codesandbox example but it didn't have any effect.

**Comment by bvaughn** [comment]
Look in the console:
```
Uncaught Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (react.js:185:13)
    at exports.useRef (react.js:290:12)
    at useUniqueId (react-resizable-panels.js:58:19)
    at PanelGroupWithForwardedRef (react-resizable-panels.js:741:21)
    at renderWithHooks (react-dom.development.js:16315:20)
    at mountIndeterminateComponent (react-dom.development.js:20084:15)
    at beginWork (react-dom.development.js:21597:18)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4151:16)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4200:18)
    at invokeGuardedCallback (react-dom.development.js:4264:33)
react-dom.development.js:18697 The above error occurred in the <PanelGroup> component:
```

https://legacy.reactjs.org/docs/error-decoder.html/?invariant=321:
> Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

**Comment by bvaughn** [comment]
This looks like it's being caused by multiple versions of React being loaded onto the page, not anything to do with this library.
